-- Batch C2 Phase 1
-- Creates baseline Snowflake objects for loading Batch C1 serving outputs.
-- Placeholders are rendered by run_phase1_setup.py.

USE ROLE {{SF_ROLE}};
USE WAREHOUSE {{SF_WAREHOUSE}};

CREATE DATABASE IF NOT EXISTS {{SF_DATABASE}};
USE DATABASE {{SF_DATABASE}};

CREATE SCHEMA IF NOT EXISTS STG;
CREATE SCHEMA IF NOT EXISTS SERVING;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE FILE FORMAT IF NOT EXISTS STG.FF_PARQUET_V1
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE
  BINARY_AS_TEXT = FALSE
  NULL_IF = ('NULL', 'null');

CREATE STAGE IF NOT EXISTS STG.GCS_TABLEAU_SERVING_V1
  URL = '{{GCS_SERVING_URL}}'
  STORAGE_INTEGRATION = {{SF_STORAGE_INTEGRATION}}
  FILE_FORMAT = (FORMAT_NAME = STG.FF_PARQUET_V1);

-- Initial empty target table for C2 load validation.
-- Contract mirrored from gold/tableau_serving/v1/serv_team_season_weather_v1.
CREATE TABLE IF NOT EXISTS SERVING.SERV_TEAM_SEASON_WEATHER_V1 (
  SEASON NUMBER(10,0),
  TEAM VARCHAR,
  TEMP_BIN VARCHAR,
  WIND_BIN VARCHAR,
  PRECIP_BIN VARCHAR,
  ROOF_ENV_BIN VARCHAR,
  WEATHER_SAMPLE VARCHAR,
  N_PLAYS NUMBER(38,0),
  N_PASS_ATTEMPTS NUMBER(38,0),
  N_RUSH_ATTEMPTS NUMBER(38,0),
  N_COMPLETIONS NUMBER(38,0),
  N_EPA_PLAYS NUMBER(38,0),
  N_GAMES NUMBER(38,0),
  N_GAMES_POINTS NUMBER(38,0),
  N_TEAM_GAMES_POINTS NUMBER(38,0),
  PASS_RATE FLOAT,
  COMPLETION_PCT FLOAT,
  EPA_PER_PLAY FLOAT,
  POINTS_PER_GAME FLOAT,
  BATCH_A_BUILD_RUN_TS VARCHAR,
  BATCH_B_BUILD_RUN_TS VARCHAR,
  SOURCE_BATCH_A_BUILD_RUN_TS VARCHAR,
  SOURCE_BATCH_B_BUILD_RUN_TS VARCHAR,
  SERVING_BUILD_RUN_TS VARCHAR,
  SERVING_VERSION VARCHAR,
  SERVING_RUN_ID VARCHAR
);
